name: Breaking News Bot

on:
  # Runs every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  
  # Allows manual trigger from GitHub UI
  workflow_dispatch:
  
  # Optional: Run on push to test
  push:
    branches: [ main ]

jobs:
  check-news:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Prevent hanging
    
    steps:
    # Step 1: Checkout code
    - name: ðŸ“¥ Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    # Step 2: Setup Python
    - name: ðŸ Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    # Step 3: Install dependencies
    - name: ðŸ“¦ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 4: Run the news bot
    - name: ðŸ¤– Run Breaking News Bot
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        echo "ðŸš€ Starting news check..."
        echo "Time: $(date)"
        echo "GitHub Actions Run ID: ${{ github.run_id }}"
        echo "========================================="
        python src/breaking_news_bot.py
    
    # Step 5: Save logs (optional)
    - name: ðŸ’¾ Save run logs
      if: always()  # Run even if previous steps fail
      run: |
        echo "Run completed at: $(date)" >> run_log.txt
        echo "Status: ${{ job.status }}" >> run_log.txt
      continue-on-error: true
